# Generated by Django 5.2.7 on 2025-11-03 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, help_text='E.g. Hybrid, Organic, Local, etc.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=7)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('count', 'Count / Bundle')], default='kg', max_length=10)),
                ('stock', models.DecimalField(decimal_places=2, help_text='Stock available (kg or count)', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vegetable_images/')),
                ('freshness_level', models.CharField(choices=[('Fresh', 'Fresh'), ('Average', 'Average'), ('Old Stock', 'Old Stock')], default='Fresh', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vegetables', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
