# Generated by Django 5.2.7 on 2025-11-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payout_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payout_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refunded_amount',
        ),
    ]
