# Generated by Django 5.2.7 on 2025-11-23 19:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_vegetable',
            name='min_bid_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum bidding price', max_digits=10),
        ),
        migrations.CreateModel(
            name='SellerCreateBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ending_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('vegetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bidding.bidding_vegetable')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_bids', to=settings.AUTH_USER_MODEL)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_bids', to='bidding.sellercreatebid')),
            ],
        ),
    ]
