# Generated by Django 5.2.7 on 2025-11-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_bidding_vegetable_min_bid_price_sellercreatebid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidding_vegetable',
            name='price',
        ),
    ]
