# Generated by Django 5.2.7 on 2025-11-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_remove_bidding_vegetable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding_vegetable',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('count', 'Count / Bundle'), ('quintal', 'quintal')], default='kg', max_length=10),
        ),
    ]
