# Generated by Django 5.2.7 on 2025-11-24 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_bidding_vegetable_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyerbid',
            options={'ordering': ['-bid_price', '-timestamp']},
        ),
    ]
