# Generated by Django 5.2.7 on 2025-11-25 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=255)),
                ('vegetable_name', models.CharField(max_length=255)),
                ('variety', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=50)),
                ('saved_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
